[package]
name = "bug_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12.1"}
bevy_asset_loader = "0.18.0"
bevy_embedded_assets = "0.9.1"

